### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by gabriel-v** [vmck/vagrant-vmck#10]
After https://github.com/vmck/vagrant-vmck/pull/9 is merged, the docker image will be huge.

Let's use multi-stage builds to only keep the installed vagrant and plugin in the final image, without all the ruby stuff.

I've tried with no avail to base the image on Alpine, but I think the only solution then would be recompiling it, since the Vagrant binary release is linked with glibc which is not present on Alpine.

**Comment by mgax** [comment]
Or remove the extra packages in the same `RUN` step.
