### ISSUE TITLE
Machine not ready for guest communication

### ISSUE THREAD

**Issue by raduklb** [vmck/vagrant-vmck#13]
Trying to run `vagrant up --provider=vmck` issues:
```
Bringing machine 'liquid-vagrant-Radus-MacBook-Pro.local' up with 'vmck' provider...
==> liquid-vagrant-Radus-MacBook-Pro.local: Vmck starting job ...
==> liquid-vagrant-Radus-MacBook-Pro.local: Vmck waiting for job 575 to be ready ...
==> liquid-vagrant-Radus-MacBook-Pro.local: Vmck job 575 is ready, waiting for ssh ...
==> liquid-vagrant-Radus-MacBook-Pro.local: Vmck got ssh access to job 575
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```
After the error was issued, the job was still running in Nomad, and trying to ssh into the VM issues the same `Guest-specific operations...` error.

**Comment by Jokeswar** [comment]
Here is the [log](https://gist.github.com/Jokeswar/0283fd122dc8ee7d4c49a13ef22d8644) of a failed `vagrant up` with the above mentioned error. What I could make of it is that the ssh daemon hasn't started yet when vagrant tries to connect. Just above [line 308](https://gist.github.com/Jokeswar/0283fd122dc8ee7d4c49a13ef22d8644#file-vagrant-up-log-L308) we get a nice error regarding ssh, and it seems that vagrant-vmck goes on ahead without trouble even thought the ssh agent is not up. I believe that someone is lying either **Nomad** or **vmck**. I do not know... Now, @mgax and @gabriel-v I got a little fix(more of a sweep under the rug) and you might not like it but until we fix this problem it will keep `vagrant up` from failing. Just add `sleep(2.5)` after this line here: 
https://github.com/vmck/vagrant-vmck/blob/2bcf97d3cffdc09f5c4dd79ee97b6ded588d817c/lib/vagrant-vmck/action/create.rb#L40

I did 20 `vagrant up` commands and none of them failed.
PS: After a failed `vagrant up`, `vagrant ssh` works just fine. This makes me believe that the plugin gets its confirmation way earlier than it should, or Nomad believes that the qemu job has a running ssh when it doesn't.

**Comment by mgax** [comment]
> Nomad believes that the qemu job has a running ssh when it doesn't.

Yes, Nomad only does a TCP healthcheck, and it talks to the qemu proxy, not the actual ssh daemon. So one option is to check if it's possible to make the healthcheck smarter, maybe switching to a [command](https://www.nomadproject.io/docs/job-specification/service.html#command) that points to a script that invokes `/usr/bin/ssh` with some creative arguments.

> I got a little fix(more of a sweep under the rug) and you might not like it but until we fix this problem it will keep `vagrant up` from failing. Just add `sleep(2.5)` after this line here:

Yeah, no, if you spend the time to look at the problem, you might as well fix it properly.

**Comment by Jokeswar** [comment]
I got a proper fix now. I used telnet to check if a port is available for communication along with some nomad env vars.

**Comment by mgax** [comment]
Coolio! Let's deploy it and monitor our server. If the problem doesn't show up in a week, close the issue.

**Comment by mgax** [comment]
Fixed in https://github.com/vmck/vmck/pull/106
